services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command: serve
    restart: unless-stopped
    environment:
      - NTFY_BASE_URL=https://ntfy.homelab.tarasa24.dev
      - NTFY_LISTEN_HTTP=0.0.0.0:8080
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
    volumes:
      - ntfy-data:/var/lib/ntfy
    ports:
      - "10.1.0.24:8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ntfy-data:
    external: true
    name: root_ntfy-data
