version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    user: 1000:1000
    ports:
      - 10.1.0.21:8096:8096
      - 10.1.0.21:8920:8920
    volumes:
      - jelllyfin_config:/config
      - /cache:/cache
      - type: bind
        source: /media
        target: /media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.homelab.tarasa24.dev

volumes:
  jelllyfin_config: