modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [200]
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"
      
  http_post_2xx:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [200]
      method: POST
      
  tcp_connect:
    prober: tcp
    timeout: 10s
    
  icmp:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: "ip4"