---
services:
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    ports:
      - "10.0.1.21:9091:9091"
    environment:
      X_AUTHELIA_CONFIG_FILTERS: expand-env,template
      X_AUTHELIA_CONFIG: /config/configuration.yml
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: '/secrets/IDENTITY_PROVIDERS_OIDC_HMAC_SECRET'
    volumes:
      - ./authelia/config:/config
      - ./authelia/secrets:/secrets
