---
- name: Configure authentik container
  hosts: lxc_authentik
  gather_facts: false

  tasks:
    - name: Copy configuration files to /etc/authentik
      ansible.builtin.copy:
        src: "../../../configs/authentik/"
        dest: /etc/authentik/
        owner: root
        group: root
        mode: "0644"

    - name: Start docker compose in the authentik container
      ansible.builtin.command:
        cmd: "docker-compose up -d"
        chdir: /etc/authentik/
        creates: /etc/authentik/docker-compose.yml
