---
- name: Configure backup server
  hosts: lxc_backup
  gather_facts: false

  vars:
    ansible_host: "{{ hostvars[inventory_hostname].ansible_host }}"
    lxc_host: "{{ hostvars[inventory_hostname].lxc_host }}"
    repositories_dir: /backup/repos
    linode_access_key: "{{ lookup('file', '../../../secrets/backup/resticprofile/access_key') }}"
    linode_secret_key: "{{ lookup('file', '../../../secrets/backup/resticprofile/secret_key') }}"
  roles:
    - role: lxc_python3

  pre_tasks:
    - name: Find all ".yaml" and ".yml" borgmatic configuration files
      local_action:
        module: find
        paths: "../../../configs/backup/borg"
        patterns: "*.yml,*.yaml"
        file_type: file
      register: borgmatic_configs
    - name: Set the config names as a variable
      ansible.builtin.set_fact:
        repositories: "{{ borgmatic_configs.files | map(attribute='path') | map('basename') | map('regex_replace', '\\.(yml|yaml)$', '') | list }}"
  tasks:
    - name: Install ssh
      ansible.builtin.apk:
        name: openssh
        state: present
    - name: Start sshd
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true
    - name: Set PubKeyAuthentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "PubKeyAuthentication yes"
        state: present
    - name: Set PasswordAuthentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "PasswordAuthentication no"
        state: present
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Install restic
      ansible.builtin.apk:
        name: restic
        state: present

    - name: Check if resticprofile is installed
      ansible.builtin.stat:
        path: /usr/local/bin/resticprofile
      register: resticprofile_installed

    - name: Install resticprofile
      block:
        - name: Curl resticprofile
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/creativeprojects/resticprofile/master/install.sh
            dest: /tmp/resticprofile.sh
            mode: 'u+x'

        - name: Compile resticprofile
          ansible.builtin.command:
            cmd: /tmp/resticprofile.sh -b /usr/local/bin
            creates: /usr/local/bin/resticprofile
      when: not resticprofile_installed.stat.exists
    - name: Create resticprofile configuration directory
      ansible.builtin.file:
        path: /etc/resticprofile
        state: directory
        mode: '0700'
    - name: Copy resticprofile configuration
      ansible.builtin.template:
        src: ../../../configs/backup/resticprofile/borg-to-linode-s3.yaml.j2
        dest: /etc/resticprofile/profiles.yaml
        mode: '0600'
    - name: Copy resticprofile password file
      ansible.builtin.copy:
        src: ../../../secrets/backup/resticprofile/restic-password.txt
        dest: /etc/resticprofile/restic-password.txt
    - name: Init restic repositories if they don't already exist
      ansible.builtin.command: resticprofile {{ item }}.init
      with_items: "{{ repositories }}"
      ignore_errors: true
      register: restic_init
    - name: Check for errors in restic init
      ansible.builtin.fail:
        msg: "Error initializing restic repository"
      when: item.rc != 0 and not ("repository master key and config already initialized" in item.stderr)
      with_items: "{{ restic_init.results }}"
    - name: Schedule restic backups
      ansible.builtin.command: resticprofile {{ item }}.schedule
      with_items: "{{ repositories }}"
    - name: Install fuse (for restic mount)
      ansible.builtin.apk:
        name: fuse
        state: present

    - name: Install borg + borgmatic
      ansible.builtin.apk:
        name: [ borgbackup, borgmatic ]
        state: present
    - name: Create backup group
      ansible.builtin.group:
        name: backup
        gid: 1000
        state: present
    - name: Create backup user
      ansible.builtin.user:
        name: backup
        group: backup
        groups:
        shell: /bin/ash
        home: /home/backup
        create_home: yes
        uid: 1000
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') | password_hash('sha512') }}"
        state: present
    - name: Create backup home directory
      ansible.builtin.file:
        path: /home/backup
        state: directory
        owner: backup
        group: backup
        mode: '0700'
    - name: Create directory for backup repositories
      ansible.builtin.file:
        path: "{{ repositories_dir }}"
        state: directory
        owner: backup
        group: backup
        mode: '0700'
    - name: Create backup ssh directory
      ansible.builtin.file:
        path: /home/backup/.ssh
        state: directory
        owner: backup
        group: backup
        mode: '0700'
    - name: Set authorized_keys
      ansible.builtin.authorized_key:
        user: backup
        key: "{{ lookup('file', '../../../secrets/backup/ssh/id_ed25519.pub') }}"
        key_options: 'command="/usr/bin/borg serve --restrict-to-path {{ repositories_dir }}",restrict'
    - name: Set authrized keys permissions
      ansible.builtin.file:
        path: /home/backup/.ssh/authorized_keys
        owner: backup
        group: backup
        mode: '0600'
        state: file

    - name: Init borg repositories if they don't already exist
      ansible.builtin.command:
        cmd: borg init --encryption=none {{ repositories_dir }}/{{ item }}
        creates: "{{ repositories_dir }}/{{ item }}/config"
      become: true
      become_user: backup
      become_method: su
      become_flags: '-s /bin/sh'
      with_items: "{{ repositories }}"

    - name: Install pyfuse3 (for borg mount)
      ansible.builtin.apk:
        name: py3-pyfuse3
        state: present
