---
- name: Configure jellyfin container
  hosts: lxc_dmz_jellyfin
  gather_facts: false
  vars:
    ansible_host: "{{ hostvars[inventory_hostname].ansible_host }}"
    lxc_host: "{{ hostvars[inventory_hostname].lxc_host }}"
  roles:
    - role: lxc_python3

  tasks:
    - name: Import ssh private key
      ansible.builtin.copy:
        src: ../../../secrets/backup/ssh/jellyfin
        dest: /root/.ssh/jellyfin
        mode: 0600

    - name: Create /etc/borgmatic directory
      ansible.builtin.file:
        dest: /etc/borgmatic
        state: directory
    - name: Copy over borgmatic configuration
      ansible.builtin.copy:
        src: ../../../configs/backup/borg/jellyfin.yaml
        dest: /etc/borgmatic/config.yaml
        mode: 0644

    - name: Import data from backup
      ansible.builtin.command:
        cmd: "borgmatic extract --archive latest --destination /"

    - name: Setup cron job for borgmatic
      ansible.builtin.cron:
        name: "Backup jellyfin config"
        job: "borgmatic --verbosity 0"
        minute: "0"
        hour: "2"
        state: present

    - name: Create directories
      ansible.builtin.file:
        dest: /etc/jellyfin
        state: directory
    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../../../configs/jellyfin/docker-compose.yml
        dest: /etc/jellyfin/docker-compose.yml
        owner: root
        group: root
        mode: 0644

    - name: Start docker compose service
      ansible.builtin.command:
        cmd: "docker compose up -d"
        chdir: /etc/jellyfin
