---
- name: Configure Alpine Docker template in LXC container
  hosts: proxmox
  gather_facts: false
  vars:
    vmid: "{{ vmid }}"

  tasks:
    - name: Set motd
      ansible.builtin.command:
        lxc-attach -n {{ vmid }} -- sh -c \
          "echo 'Welcome to the Alpine Docker template' > /etc/motd"
      register: set_motd
      changed_when: true

    - name: Update the package cache
      ansible.builtin.command:
        lxc-attach -n {{ vmid }} -- sh -c "apk update"
      register: update_cache
      changed_when: update_cache.stdout.find('skipping') == -1

    - name: Install ssh in the LXC container
      ansible.builtin.command:
        lxc-attach -n {{ vmid }} -- sh -c \
          "apk add openssh &&
          rc-update add sshd &&
          rc-service sshd start"
      register: install_ssh
      changed_when: install_ssh.stdout.find('ERROR') == -1

    - name: Install Docker in the LXC container
      ansible.builtin.command:
        lxc-attach -n {{ vmid }} -- sh -c \
          "apk add docker &&
          rc-update add docker &&
          rc-service docker start"
      register: install_docker
      changed_when: install_docker.stdout.find('ERROR') == -1

    - name: Stop the container
      ansible.builtin.command:
        "pct stop {{ vmid }}"
      register: create_template
      changed_when: create_template.stdout.find('ERROR') == -1

    - name: Create a template from the container
      ansible.builtin.command:
        "pct set {{ vmid }} --template 1"
      register: create_template
      changed_when: create_template.stdout.find('ERROR') == -1
