---
- name: Configure Alpine Docker template in LXC container
  hosts: lxc_docker_template
  gather_facts: false
  vars:
    ansible_host: "{{ hostvars[inventory_hostname].ansible_host }}"
    lxc_host: "{{ hostvars[inventory_hostname].lxc_host }}"
  roles:
    - role: lxc_python3

  tasks:
    - name: Install Docker
      ansible.builtin.apk:
        name: docker
        state: present
        update_cache: true

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Stop the container
      ansible.builtin.command:
        "pct stop {{ lxc_host }}"
      delegate_to: "{{ ansible_host }}"
      changed_when: false

    - name: Create Docker template
      ansible.builtin.command:
        "pct set {{ lxc_host }} --template 1"
      delegate_to: "{{ ansible_host }}"
      changed_when: false