---
- name: Configure private docker host
  hosts: lxc_private-docker-host
  gather_facts: false
  vars:
    ansible_host: "{{ hostvars[inventory_hostname].ansible_host }}"
    lxc_host: "{{ hostvars[inventory_hostname].lxc_host }}"
    ip_range: [
      "10.0.1.21",
      "10.0.1.22",
      "10.0.1.23",
      "10.0.1.24",
      "10.0.1.25",
      "10.0.1.26",
      "10.0.1.27",
      "10.0.1.28",
      "10.0.1.29",
      "10.0.1.30"
    ]
  roles:
    - role: lxc_python3
    - role: borgmatic

  tasks:
    - name: Assign IP range to virtual nics if not already assigned
      shell: ip addr add {{ ip }} dev eth0:{{ index }} || true
      loop: "{{ ip_range }}"
      loop_control:
        loop_var: ip
        index_var: index

    - name: Have ip addr add commands run at boot
      copy:
        content: |
          {% for ip in ip_range %}
          ip addr add {{ ip }} dev eth0:{{ loop.index0 }}
          {% endfor %}
        dest: /etc/local.d/assign-ips.start
        mode: "0755"

    - name: Enable local.d scripts
      ansible.builtin.command: rc-update add local default

    - name: Stop and remove existing containers
      shell: docker compose down || true

    - name: Copy over configs
      copy:
        src: "../../../configs/private-docker-host/"
        dest: "/root/"
        force: yes

    - name: Find each docker-compose.yaml in relation to /root
      find:
        paths: /root
        patterns: "docker-compose.yaml"
        recurse: yes
      register: docker_compose_files
    - name: Create .env file which contains COMPOSE_FILE=... for each docker-compose.yaml
      copy:
        content: "COMPOSE_FILE={{ compose_files }}"
        dest: "/root/.env"
      vars:
        compose_files: "{{ docker_compose_files.files | map(attribute='path') | join(':') }}"

    - name: Pull images
      shell: docker-compose pull
      args:
        chdir: /root
      timeout: 1200

    - name: Start containers
      shell: docker-compose up -d
      args:
        chdir: /root

