services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/config/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.max-block-duration=30m
      - --storage.tsdb.min-block-duration=30m
      - --web.enable-lifecycle
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus/prometheus.yml:/etc/config/prometheus.yml
      - prometheus-data:/prometheus
    ports:
        - 9081:9090
    restart: always

  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.38.0
    container_name: thanos-sidecar
    depends_on:
      - prometheus
      - minio
    command:
      - sidecar
      - --tsdb.path=/prometheus
      - --prometheus.url=http://prometheus:9090
      - --grpc-address=0.0.0.0:10091
      - --http-address=0.0.0.0:10902
      - --objstore.config-file=/etc/thanos/objstore.yml
    volumes:
      - prometheus-data:/prometheus
      - ./thanos:/etc/thanos
    restart: always

  thanos-querier:
    image: quay.io/thanos/thanos:v0.38.0
    container_name: thanos-querier
    depends_on:
      - thanos-sidecar
      - thanos-store
    command:
      - query
      - --grpc-address=0.0.0.0:10091
      - --http-address=0.0.0.0:10902
      - --endpoint=thanos-sidecar:10091
      - --endpoint=thanos-store:10091
    ports:
      - 10902:10902
    restart: always

  thanos-store:
    image: quay.io/thanos/thanos:v0.38.0
    container_name: thanos-store
    depends_on:
      - minio
    command:
      - store
      - --grpc-address=0.0.0.0:10091
      - --http-address=0.0.0.0:10902
      - --data-dir=/tmp/thanos/store
      - --objstore.config-file=/etc/thanos/objstore.yml
    volumes:
      - ./thanos:/etc/thanos
    restart: always

  thanos-compactor:
    image: quay.io/thanos/thanos:v0.38.0
    container_name: thanos-compactor
    depends_on:
      - minio
    command:
      - compact
      - --objstore.config-file=/etc/thanos/objstore.yml
      - --data-dir=/tmp/thanos/compact
      - --wait
    volumes:
      - ./thanos:/etc/thanos
    restart: always

  loki:
    image: grafana/loki:2.9.2
    depends_on:
      - minio
    container_name: loki
    user: 0:0
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - /var/lib/monitoring-fast/loki:/loki
    ports:
      - 3100:3100
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - /mnt/monitoring-cold/minio:/data
    ports:
      - "9000:9000"
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; do sleep 1; done;
        /usr/bin/mc mb -p myminio/loki-index;
        /usr/bin/mc mb -p myminio/loki-chunks;
        /usr/bin/mc mb -p myminio/thanos;
        exit 0;
      "

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: 0:0
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/grafana.ini
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
