services:
  # Promtail for log collection
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./root/promtail/config.yml:/etc/promtail/config.yml
    restart: always
