- name: Run borg backup on all configured servers to have the most up-to-date backup
  hosts: "{{ variable_host | default('all:!proxmox:!linode_dmz_bastion') }}"
  ignore_unreachable: true
  gather_facts: false

  tasks:
    - name: Check if borgmatic is installed
      ansible.builtin.package:
        name: borgmatic
      register: borgmatic_installed
    - name: Check if borgmatic is configured
      ansible.builtin.stat:
        path: /etc/borgmatic/config.yaml
      register: borgmatic_configured

    - name: Run backup with borgmatic
      ansible.builtin.command:
        cmd: borgmatic --verbosity 1 --stats
      when: borgmatic_installed is defined and borgmatic_installed is succeeded and borgmatic_configured.stat.exists
      changed_when: false
