auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: s3
    cache_location: /loki/boltdb-cache

  filesystem:
    directory: /loki/chunks

  aws:
    s3: http://minio:9000/loki
    s3forcepathstyle: true
    insecure: true
    access_key_id: minioadmin
    secret_access_key: minioadmin

compactor:
  working_directory: /loki/compactor
  shared_store: s3

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days
