apiVersion: 1

datasources:
  - name: Thanos
    type: prometheus
    url: http://thanos-querier:10902
    access: proxy

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy

  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    jsonData:
      version: Flux
