---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  address: "tcp://:9091"
  endpoints:
    authz:
      auth-request:
        implementation: "AuthRequest"

log:
  level: "debug"

totp:
  issuer: "tarasa24.dev"

# identity_validation:
#   reset_password:
#     jwt_secret: 'a_very_important_secret'

authentication_backend:
  file:
    path: "/config/users_database.yml"

access_control:
  default_policy: "deny"
  rules:
    - domain: "homelab.tarasa24.dev"
      policy: "bypass"
      resources:
        - "^(.*)$$" # All resources

session:
  # secret: 'insecure_session_secret'
  cookies:
    - domain: "homelab.tarasa24.dev"
      authelia_url: "https://auth.homelab.tarasa24.dev"
      default_redirection_url: "https://www.homelab.tarasa24.dev"

regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  # encryption_key: 'you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this'
  local:
    path: "/config/db.sqlite3"

notifier:
  filesystem:
    filename: "/config/notification.txt"

identity_providers:
  oidc:
    # hmac_secret:
    jwks:
      - key_id: "default"
        algorithm: "RS256"
        use: "sig"
        key: {{ secret "/secrets/private.pem" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/secrets/public.crt" | mindent 10 "|" | msquote }}

    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    clients:
      - client_id: "jellyfin"
        client_name: "Jellyfin"
        client_secret: "$$pbkdf2-sha512$$310000$$M1o6uYU/oOYaj29otbR3Xg$$vM91QqHObirMXp8D9vVvGN/2iAnuEM72wow6KI7m4XwnsNTL9qJaTWr5bN8AF0jPxdYZp2AcslK9EVnInJsKNA"
        public: false
        authorization_policy: "one_factor"
        require_pkce: true
        pkce_challenge_method: "S256"
        redirect_uris:
          - "https://jellyfin.homelab.tarasa24.dev/sso/OID/redirect/Authelia"
        scopes:
          - "openid"
          - "profile"
          - "groups"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_post"
