---
- name: Install Docker
  community.general.apk:
    name: [docker, docker-compose]
    state: present
    update_cache: true

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
