---
- name: Install Docker
  community.general.apk:
    name: [docker, docker-compose]
    state: present
    update_cache: true
  retries: 3

- name: Ensure /etc/docker directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: Write daemon.json with metrics endpoint enabled
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "metrics-addr": "0.0.0.0:9323"
      }
    mode: "0644"

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
