services:
  # Promtail for log collection
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./root/promtail/config.yml:/etc/promtail/config.yml
    restart: always
