services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    restart: always

    networks:
      - open-internet
    volumes:
      - /root/arr_stack/wg0.conf:/config/wg_confs/wg0.conf
      - /lib/modules:/lib/modules:ro
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    ports:
      - 10.0.1.23:9696:9696 #prowlarr
      - 10.0.1.23:8989:8989 #sonarr
      - 10.0.1.23:7878:7878 #radarr
      - 10.0.1.23:6767:6767 #bazarr
      - 10.0.1.23:8080:8080 #qbittorrent
  prowlarr:
    network_mode: service:wireguard
    depends_on:
      - wireguard
    image: lscr.io/linuxserver/prowlarr:nightly
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - prowlarr-config:/config
    restart: always
  flaresolverr:
    network_mode: service:wireguard
    depends_on:
      - wireguard
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    restart: always

  sonarr:
    network_mode: service:wireguard
    depends_on:
      - wireguard
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - sonarr-config:/config
      - /media/shows:/shows
      - /downloads:/downloads
    restart: always
  radarr:
    network_mode: service:wireguard
    depends_on:
      - wireguard
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - radarr-config:/config
      - /media/movies:/movies
      - /downloads:/downloads
    restart: always
  bazarr:
    network_mode: service:wireguard
    depends_on:
      - wireguard
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - bazarr-config:/config
      - /media/movies:/movies
      - /media/shows:/shows
    restart: always

  qbittorrent:
    network_mode: service:wireguard
    depends_on:
      - wireguard
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - qbittorrent-config:/config
      - /downloads:/downloads
    restart: always

networks:
  open-internet:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  prowlarr-config:
  sonarr-config:
  radarr-config:
  bazarr-config:
  qbittorrent-config: