location:
    source_directories:
        - /var/lib/docker/volumes/root_jellyfin_config/_data
        - /var/lib/docker/volumes/root_radicale_data/_data
        - /var/lib/docker/volumes/root_immich_database/_data
    repositories:
        - ssh://backup@10.0.1.3/backup/repos/dmz_docker-host

storage:
    compression: "zlib,6"
    ssh_command: "ssh -i /root/.ssh/id_ed25519 -o StrictHostKeychecking=no"
    unknown_unencrypted_repo_access_is_ok: true

retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
    keep_yearly: 2
    prefix: "{hostname}-"

consistency:
    checks:
        - "repository"
        - "archives"
    check_last: 3

hooks:
    before_backup:
        - "cd /root && docker-compose stop jellyfin"
        - "cd /root && docker-compose stop radicale"
        - "cd /root && docker-compose stop immich-database"
    after_backup:
        - "cd /root && docker-compose up -d jellyfin"
        - "cd /root && docker-compose up -d radicale"
        - "cd /root && docker-compose up -d immich-database"
