source_directories:
  - /var/lib/docker/volumes/root_jellyfin_config/_data
  - /var/lib/docker/volumes/root_radicale_data/_data
  - /var/lib/docker/volumes/root_immich_database/_data
  - /var/lib/docker/volumes/root_ntfy-data/_data

repositories:
  - path: ssh://backup@10.0.30.13/backup/repos/dmz_docker-host

compression: zlib,6
ssh_command: ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no
unknown_unencrypted_repo_access_is_ok: true

keep_daily: 7
keep_weekly: 4
keep_monthly: 6
keep_yearly: 2
archive_name_format: "{hostname}-{now}"
match_archives: "{hostname}-*"

checks:
  - name: repository
  - name: archives
check_last: 3

before_backup:
  - cd /root && docker compose stop jellyfin
  - cd /root && docker compose stop radicale
  - cd /root && docker compose stop immich-database
  - cd /root && docker compose stop ntfy
after_backup:
  - cd /root && docker compose start jellyfin
  - cd /root && docker compose start radicale
  - cd /root && docker compose start immich-database
  - cd /root && docker compose start ntfy
on_error:
  - cd /root && docker compose start jellyfin
  - cd /root && docker compose start radicale
  - cd /root && docker compose start immich-database
  - cd /root && docker compose start ntfy
