location:
  source_directories:
    - /var/lib/docker/volumes/root_grafana-data/_data
    - /var/lib/docker/volumes/root_uptime-kuma-data/_data
  repositories:
    - ssh://backup@10.0.1.3/backup/repos/monitoring

storage:
  compression: zlib,6
  ssh_command: ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no
  unknown_unencrypted_repo_access_is_ok: true

retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
  keep_yearly: 2
  prefix: "{hostname}-"

consistency:
  checks:
    - repository
    - archives
  check_last: 3

hooks:
  before_backup:
    - cd /root && docker-compose stop grafana
    - cd /root && docker-compose stop uptime-kuma
  after_backup:
    - cd /root && docker-compose up -d grafana
    - cd /root && docker-compose up -d uptime-kuma
