location:
    source_directories:
        - /var/lib/docker/volumes/root_mealie-data/_data

        - /var/lib/docker/volumes/root_vaultwarden-data/_data

        - /var/lib/docker/volumes/root_prowlarr-config/_data
        - /var/lib/docker/volumes/root_sonarr-config/_data
        - /var/lib/docker/volumes/root_radarr-config/_data
        - /var/lib/docker/volumes/root_bazarr-config/_data
        - /var/lib/docker/volumes/root_qbittorrent-config/_data

        - /var/lib/docker/volumes/root_archivist-es/_data
        - /var/lib/docker/volumes/root_archivist-redis/_data
    repositories:
        - ssh://backup@10.0.1.3/backup/repos/private-docker-host

storage:
    compression: "zlib,6"
    ssh_command: "ssh -i /root/.ssh/id_ed25519 -o StrictHostKeychecking=no"
    unknown_unencrypted_repo_access_is_ok: true

retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
    keep_yearly: 2
    prefix: "{hostname}-"

consistency:
    checks:
        - "repository"
        - "archives"
    check_last: 3

hooks:
    before_backup:
        - "cd /root && docker-compose stop mealie"
        - "cd /root && docker-compose stop vaultwarden"
        - "cd /root && docker-compose stop prowlarr sonarr radarr bazarr qbittorrent"
        - "cd /root && docker-compose stop tubearchivist"
    after_backup:
        - "cd /root && docker-compose up -d mealie"
        - "cd /root && docker-compose up -d vaultwarden"
        - "cd /root && docker-compose up -d prowlarr sonarr radarr bazarr qbittorrent"
        - "cd /root && docker-compose up -d tubearchivist"
