location:
    source_directories:
        - /var/lib/docker/volumes/root_mealie-data/_data

        - /var/lib/docker/volumes/root_vaultwarden-data/_data

        - /var/lib/docker/volumes/root_prowlarr-config/_data
        - /var/lib/docker/volumes/root_sonarr-config/_data
        - /var/lib/docker/volumes/root_radarr-config/_data
        - /var/lib/docker/volumes/root_bazarr-config/_data
        - /var/lib/docker/volumes/root_qbittorrent-config/_data
    repositories:
        - ssh://backup@10.0.1.3/backup/repos/private-docker-host

storage:
    compression: "zlib,6"
    ssh_command: "ssh -i /root/.ssh/id_ed25519 -o StrictHostKeychecking=no"
    unknown_unencrypted_repo_access_is_ok: true

retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
    keep_yearly: 2
    prefix: "{hostname}-"

consistency:
    checks:
        - "repository"
        - "archives"
    check_last: 3

hooks:
    before_backup:
        - "docker ps --filter 'name=mealie' --filter 'status=running' --format '{{.Names}}' | grep -w mealie && docker stop mealie && echo 'mealie stopped' || echo 'mealie already stopped or does not exist'"

        - "docker ps --filter 'name=vaultwarden' --filter 'status=running' --format '{{.Names}}' | grep -w vaultwarden && docker stop vaultwarden && echo 'vaultwarden stopped' || echo 'vaultwarden already stopped or does not exist'"

        - "docker ps --filter 'name=prowlarr' --filter 'status=running' --format '{{.Names}}' | grep -w prowlarr && docker stop prowlarr && echo 'prowlarr stopped' || echo 'prowlarr already stopped or does not exist'"
        - "docker ps --filter 'name=sonarr' --filter 'status=running' --format '{{.Names}}' | grep -w sonarr && docker stop sonarr && echo 'sonarr stopped' || echo 'sonarr already stopped or does not exist'"
        - "docker ps --filter 'name=radarr' --filter 'status=running' --format '{{.Names}}' | grep -w radarr && docker stop radarr && echo 'radarr stopped' || echo 'radarr already stopped or does not exist'"
        - "docker ps --filter 'name=bazarr' --filter 'status=running' --format '{{.Names}}' | grep -w bazarr && docker stop bazarr && echo 'bazarr stopped' || echo 'bazarr already stopped or does not exist'"
        - "docker ps --filter 'name=qbittorrent' --filter 'status=running' --format '{{.Names}}' | grep -w qbittorrent && docker stop qbittorrent && echo 'qbittorrent stopped' || echo 'qbittorrent already stopped or does not exist'"
    after_backup:
        - "docker inspect -f '{{.State.Running}}' mealie | grep false && docker start mealie && echo 'mealie started' || echo 'mealie already running or does not exist'"

        - "docker inspect -f '{{.State.Running}}' vaultwarden | grep false && docker start vaultwarden && echo 'vaultwarden started' || echo 'vaultwarden already running or does not exist'"

        - "docker inspect -f '{{.State.Running}}' prowlarr | grep false && docker start prowlarr && echo 'prowlarr started' || echo 'prowlarr already running or does not exist'"
        - "docker inspect -f '{{.State.Running}}' sonarr | grep false && docker start sonarr && echo 'sonarr started' || echo 'sonarr already running or does not exist'"
        - "docker inspect -f '{{.State.Running}}' radarr | grep false && docker start radarr && echo 'radarr started' || echo 'radarr already running or does not exist'"
        - "docker inspect -f '{{.State.Running}}' bazarr | grep false && docker start bazarr && echo 'bazarr started' || echo 'bazarr already running or does not exist'"
        - "docker inspect -f '{{.State.Running}}' qbittorrent | grep false && docker start qbittorrent && echo 'qbittorrent started' || echo 'qbittorrent already running or does not exist'"
