---
- name: Figure out which package manager to use (apk or apt)
  ansible.builtin.command: lxc-attach {{ lxc_host }} -- cat /etc/os-release
  register: os_release
  delegate_to: "{{ ansible_host }}"
  changed_when: false

- block:
    - name: Update package manager cache
      ansible.builtin.command: lxc-attach {{ lxc_host }} -- apk update
      delegate_to: "{{ ansible_host }}"
      retries: 3
      timeout: 60
    - name: Install python via apk (if is Alpine)
      ansible.builtin.command: lxc-attach {{ lxc_host }} -- apk add python3 py3-pip
      delegate_to: "{{ ansible_host }}"
      retries: 3
      timeout: 60
  when: os_release.stdout_lines is search("Alpine")

- block:
    - name: Update package manager cache
      ansible.builtin.command: lxc-attach {{ lxc_host }} -- apt update
      delegate_to: "{{ ansible_host }}"
      retries: 3
      timeout: 60
    - name: Install python via apt (if is Ubuntu)
      ansible.builtin.command: lxc-attach {{ lxc_host }} -- apt install -y python3 python3-pip
      delegate_to: "{{ ansible_host }}"
      retries: 60
  when: os_release.stdout_lines is search("Debian|Ubuntu")
