services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.4.1
    container_name: mealie
    restart: always
    ports:
        - "10.0.1.24:80:9000"
    volumes:
      - mealie-data:/app/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`mealie.lan.tarasa24.dev`)"
      - "traefik.http.routers.mealie.entrypoints=https"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.routers.mealie.middlewares=hsts@file"
      - "traefik.http.middlewares.hsts.headers.customrequestheaders.Host=10.0.1.24:80"
    environment:
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: Europe/Prague
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.lan.tarasa24.dev
      OIDC_AUTH_ENABLED: True
      OIDC_CLIENT_ID: mealie
      OIDC_CONFIGURATION_URL: https://auth.homelab.tarasa24.dev/.well-known/openid-configuration
    secrets:
      - OIDC_CLIENT_SECRET

volumes:
  mealie-data:
    external: true
    name: root_mealie-data

secrets:
  OIDC_CLIENT_SECRET:
    file: ./mealie/secrets/OIDC_CLIENT_SECRET
